CREATE TABLE REGIONS(
	REGION_ID TINYINT PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL
)

CREATE TABLE COUNTRIES(
	COUNTRY_ID CHAR(2) PRIMARY KEY,
	NAME VARCHAR(40) NOT NULL,
	REGION_ID TINYINT FOREIGN KEY REFERENCES REGIONS(REGION_ID)
	ON DELETE SET NULL
)

CREATE TABLE JOBS(
	JOB_ID VARCHAR(10) PRIMARY KEY,
	JOB_TITLE VARCHAR(35) NOT NULL,
	MIN_SALARY NUMERIC(6),
	MAX_SALARY NUMERIC(6)
)

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	PRICE NUMERIC(8, 2) NOT NULL,
	DESCR VARCHAR(2000)	
)

CREATE TABLE CUSTOMERS(
	CUSTOMER_ID NUMERIC(6) PRIMARY KEY,
	COUNTRY_ID CHAR(2) FOREIGN KEY REFERENCES COUNTRIES(COUNTRY_ID) NOT NULL,
	FNAME VARCHAR(20) NOT NULL,
	LNAME VARCHAR(20) NOT NULL,
	[ADDRESS] TEXT,
	EMAIL VARCHAR(30),
	GENDER CHAR(1) CHECK (GENDER IS NULL OR GENDER IN ('M', 'F'))
)

CREATE TABLE DEPARTMENTS(
	DEPARTMENT_ID INT PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	MANAGER_ID INT,
	COUNTRY_ID CHAR(2) FOREIGN KEY REFERENCES COUNTRIES(COUNTRY_ID) NOT NULL,
	CITY VARCHAR(30) NOT NULL,
	[STATE] VARCHAR(25),
	[ADDRESS] VARCHAR(40),
	POSTAL_CODE VARCHAR(12)
)

CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT PRIMARY KEY,
	FNAME VARCHAR(20) NOT NULL,
	LNAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(25) NOT NULL UNIQUE,
	PHONE VARCHAR(25),
	HIRE_DATE DATETIME NOT NULL,
	SALARY NUMERIC(8, 2) NOT NULL CHECK (SALARY > 0),
	JOB_ID VARCHAR(10) FOREIGN KEY REFERENCES JOBS(JOB_ID),
	MANAGER_ID INT FOREIGN KEY REFERENCES EMPLOYEES(EMPLOYEE_ID),
	DEPARTMENT_ID INT DEFAULT 1000 
	FOREIGN KEY REFERENCES DEPARTMENTS(DEPARTMENT_ID) 
	ON DELETE SET DEFAULT
)

ALTER TABLE DEPARTMENTS 
ADD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
	ORDER_DATE DATETIME NOT NULL,
	CUSTOMER_ID NUMERIC(6) FOREIGN KEY REFERENCES CUSTOMERS(CUSTOMER_ID) NOT NULL,
	EMPLOYEE_ID INT FOREIGN KEY REFERENCES EMPLOYEES(EMPLOYEE_ID) NOT NULL,
	SHIP_ADDRESS VARCHAR(150)
)

CREATE TABLE ORDER_ITEMS(
	ORDER_ID INT NOT NULL FOREIGN KEY REFERENCES ORDERS(ORDER_ID) 
	ON DELETE CASCADE,
	PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCTS(PRODUCT_ID) NOT NULL,
	UNIT_PRICE NUMERIC(8, 2) NOT NULL,
	QUANTITY NUMERIC(8) NOT NULL,
	CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY(ORDER_ID, PRODUCT_ID)
)

INSERT INTO REGIONS (NAME, REGION_ID)
VALUES ('Eastern Europe', 1)

INSERT INTO COUNTRIES
VALUES ('BG', 'Bulgaria', 1)

SELECT c.FNAME + ' ' + c.LNAME AS [CustomerName],
	   o.ORDER_DATE,
	   o.SHIP_ADDRESS,
	   c.ADDRESS AS [CustomerAddress],
	   co.NAME AS [CustomerCountryName]
  FROM ORDERS AS o
  JOIN CUSTOMERS AS c
	ON c.CUSTOMER_ID = o.CUSTOMER_ID
  JOIN COUNTRIES AS co
	ON co.COUNTRY_ID = c.COUNTRY_ID

SELECT e.FNAME + ' ' + e.LNAME AS [EmployeeName],
	   j.JOB_TITLE,
	   d.NAME AS [DepartmentName]
  FROM EMPLOYEES AS e
  JOIN JOBS AS j
	ON j.JOB_ID = e.JOB_ID
  JOIN DEPARTMENTS AS d
	ON d.DEPARTMENT_ID = e.DEPARTMENT_ID