  SELECT o.ORDER_ID,
		 o.ORDER_DATE,
		 SUM(oi.UNIT_PRICE * oi.QUANTITY) AS [OrderPrice]
    FROM ORDERS AS o
    JOIN ORDER_ITEMS AS oi
  	  ON oi.ORDER_ID = o.ORDER_ID
   WHERE YEAR(o.ORDER_DATE) = 2000
GROUP BY o.ORDER_ID, o.ORDER_DATE

   SELECT e.FNAME + ' ' + e.LNAME AS [Employee Name],
   	      COUNT(o.ORDER_ID) AS [Count Orders]
     FROM EMPLOYEES AS e
LEFT JOIN ORDERS AS o
	   ON o.EMPLOYEE_ID = e.EMPLOYEE_ID
 GROUP BY e.FNAME + ' ' + e.LNAME


SELECT FNAME
  FROM CUSTOMERS
INTERSECT 
SELECT FNAME
  FROM EMPLOYEES
ORDER BY FNAME

SELECT DISTINCT FNAME
  FROM CUSTOMERS
 WHERE FNAME = ANY(SELECT FNAME FROM EMPLOYEES)
ORDER BY FNAME

--Doing it with IN is a slower operation
SELECT DISTINCT FNAME 
  FROM CUSTOMERS
 WHERE FNAME IN (SELECT FNAME FROM EMPLOYEES)
ORDER BY FNAME

SELECT DISTINCT FNAME 
  FROM CUSTOMERS AS c
 WHERE EXISTS (SELECT * FROM EMPLOYEES AS e WHERE e.FNAME = c.FNAME)
ORDER BY FNAME


/*Изведете имената на държавите, в които има клиенти и отдели на фирмата */

SELECT co.NAME
  FROM COUNTRIES AS co
 WHERE EXISTS (SELECT * FROM CUSTOMERS AS cu WHERE cu.COUNTRY_ID = co.COUNTRY_ID) AND
	   EXISTS (SELECT * FROM DEPARTMENTS AS d WHERE d.COUNTRY_ID = co.COUNTRY_ID)

SELECT NAME
  FROM COUNTRIES AS c
  JOIN (
SELECT c.COUNTRY_ID 
  FROM CUSTOMERS AS c
INTERSECT
SELECT d.COUNTRY_ID
  FROM DEPARTMENTS AS d
) AS r
    ON r.COUNTRY_ID = c.COUNTRY_ID

SELECT DISTINCT co.NAME
  FROM COUNTRIES AS co
  JOIN CUSTOMERS AS cu
    ON cu.COUNTRY_ID = co.COUNTRY_ID
  JOIN DEPARTMENTS AS d
    ON d.COUNTRY_ID = cu.COUNTRY_ID

/*Изведете всички малки имена на клиенти, които не съвпадата с малките имена на служители */
SELECT FNAME
  FROM CUSTOMERS
EXCEPT
SELECT FNAME
  FROM EMPLOYEES

SELECT DISTINCT FNAME
  FROM CUSTOMERS 
 WHERE FNAME <> ALL (SELECT FNAME FROM EMPLOYEES)

SELECT DISTINCT FNAME 
  FROM CUSTOMERS
 WHERE FNAME NOT IN (SELECT FNAME FROM EMPLOYEES)
ORDER BY FNAME

SELECT DISTINCT FNAME 
  FROM CUSTOMERS AS c
 WHERE NOT EXISTS (SELECT * FROM EMPLOYEES AS e WHERE e.FNAME = c.FNAME)
ORDER BY FNAME

/*Изведете имената на държавите, в които има клиенти и няма отдели на фирмата*/

SELECT NAME
  FROM COUNTRIES AS c
  JOIN
	(
	SELECT COUNTRY_ID
	  FROM COUNTRIES
	INTERSECT
	SELECT COUNTRY_ID
	  FROM CUSTOMERS
	EXCEPT 
	SELECT COUNTRY_ID
	  FROM DEPARTMENTS
	) AS r
	ON r.COUNTRY_ID = c.COUNTRY_ID

SELECT DISTINCT co.NAME
  FROM COUNTRIES AS co
  JOIN CUSTOMERS AS cu
    ON cu.COUNTRY_ID = co.COUNTRY_ID
LEFT JOIN DEPARTMENTS AS d
	ON d.COUNTRY_ID = co.COUNTRY_ID
 WHERE d.COUNTRY_ID IS NULL

 SELECT DISTINCT co.NAME
  FROM COUNTRIES AS co
 WHERE EXISTS (SELECT * FROM CUSTOMERS AS c WHERE c.COUNTRY_ID = co.COUNTRY_ID) AND
 NOT EXISTS (SELECT * FROM DEPARTMENTS AS d WHERE d.COUNTRY_ID = co.COUNTRY_ID)

/*Изведете имената и датата на назначаване на последния назначен служител*/
SELECT TOP 1 e.FNAME + ' ' + e.LNAME AS [Employee Name],
	   e.HIRE_DATE
  FROM EMPLOYEES AS e
  JOIN 
	  (
	  SELECT MAX(HIRE_DATE) AS [HIRE_DATE]
		FROM EMPlOYEES
	  ) AS r
	ON r.HIRE_DATE = e.HIRE_DATE
ORDER BY e.HIRE_DATE DESC

--WITH TIES returns all the records not only the first one
SELECT TOP 1 WITH TIES FNAME + ' ' + LNAME AS [Employee Name],
	   HIRE_DATE
  FROM EMPLOYEES
 WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM EMPLOYEES)
ORDER BY HIRE_DATE DESC

/*Изведете имената на клиентите, номерата и стойността на най-скъпата и най-евтината поръчки*/

SELECT c.FNAME + ' ' + c.LNAME AS [EmployeeName]
  FROM CUSTOMERS AS c
  JOIN ORDERS AS o
	ON o.CUSTOMER_ID = c.CUSTOMER_ID
  JOIN (SELECT oi.ORDER_ID,
      		   SUM(oi.QUANTITY * oi.UNIT_PRICE) AS [OrderPrice]
          FROM ORDER_ITEMS AS oi
      GROUP BY oi.ORDER_ID) AS r
	ON r.ORDER_ID = o.ORDER_ID
GROUP BY c.FNAME + ' ' + c.LNAME
ORDER BY r.OrderPrice DESC
UNION
SELECT c.FNAME + ' ' + c.LNAME AS [EmployeeName],
	   MIN(r.[OrderPrice]) AS [TotalPrice]
  FROM CUSTOMERS AS c
  JOIN ORDERS AS o
	ON o.CUSTOMER_ID = c.CUSTOMER_ID
  JOIN (SELECT oi.ORDER_ID,
      		   SUM(oi.QUANTITY * oi.UNIT_PRICE) AS [OrderPrice]
          FROM ORDER_ITEMS AS oi
      GROUP BY oi.ORDER_ID) AS r
	ON r.ORDER_ID = o.ORDER_ID
GROUP BY c.FNAME + ' ' + c.LNAME